apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: obbua/sample-project:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - name: myappnodeport
    port:  80
    targetPort:  8080